reports/urls.py
from django.urls import path
from .views import (create_report_view, ReportslistView,
                    ReportDetailView, delete_report, render_pdf_view)

app_name = "reports"

urlpatterns = [
    path('create_report/', create_report_view, name="create_report"),
    path('list/', ReportslistView.as_view(), name="list"),
    path('detail/<int:pk>', ReportDetailView.as_view(), name="detail"),
    path('delete/', delete_report, name="delete_report"),
    path('render_pdf/<int:pk>', render_pdf_view, name="pdf_view"),

]

root/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import register, readme_view
from django.contrib.auth import views as auth_views

app_name = 'root_space'

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('sales.urls')),  # home page hosting
    path("customers/", include('customers.urls')),
    path("profile/", include('profiles.urls')),
    path("reports/", include('reports.urls')),
    path('regster/', register, name='register_user'),
    path('login/', auth_views.LoginView.as_view(template_name='root/login.html'), name='login_user'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout_user'),
    path('readme/', readme_view, name='readme_view'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

reports/models.py
from django.db import models
# from django.urls import reverse
from django.shortcuts import reverse

from profiles.models import Profile
from root.utils import customer_image_file_path


class Report(models.Model):
    name = models.CharField(max_length=100)
    # generate custom name for image
    image = models.ImageField(upload_to=customer_image_file_path, blank=True)
    remarks = models.TextField()
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{str(self.name)} by {str(self.author.user)} at {self.created.strftime('%d/%m/%Y')}"

    def get_absolute_url(self):
        return reverse('reports:detail', kwargs={"pk": self.pk})

reports/forms.py
from django import forms
from .models import Report


class ReportForm(forms.ModelForm):
    remarks = forms.CharField(widget=forms.Textarea(attrs={
        "id": "report_text",
        "rows": "3",
        'placeholder': 'Please enter report here ... '
    }))

    name = forms.CharField(
        widget=forms.TextInput(attrs={
            'placeholder': 'Report name',
            "id": "report_name",
        }),
        label="Report name",
        required=True)

    class Meta:
        model = Report
        fields = ('name', 'remarks',)

reports/views.py
from django.shortcuts import render, get_object_or_404
from django.template.loader import get_template
from xhtml2pdf import pisa
from profiles.models import Profile
from django.http import JsonResponse, HttpResponse
from django.contrib.auth.decorators import login_required
from .models import Report
from .utils import convert_image
from django.views.generic import ListView, DetailView
from .utils import link_callback
from django.contrib import messages


@login_required
def create_report_view(request):
    if request.is_ajax():
        name = request.POST.get('name')
        remarks = request.POST.get('remarks')
        b64_image = request.POST.get('image')  # get image from html in b64 format
        image = convert_image(b64_image)  # convert from b64 to db acceptable img
        author = Profile.objects.get(user=request.user)

        Report.objects.create(
            name=name,
            image=image,
            remarks=remarks,
            author=author
        )

        return JsonResponse({
            "msg": "got data"
        })

    return JsonResponse({
        "msg": "error in create_report_view"
    })


class ReportslistView(ListView):
    model = Report
    ordering = ['-created']
    template_name = 'reports/list.html'
    context_object_name = 'reports_list'


class ReportDetailView(DetailView):
    model = Report
    template_name = 'reports/detail.html'
    context_object_name = 'report_obj'


def delete_report(request):
    if request.is_ajax():
        pk = request.POST.get('pk')
        report = Report.objects.get(pk=pk)

        # this user can delete ?
        if request.user == report.author.user:
            report.delete()
            messages.success(request, f'report was completely deleted !')
            # django das not redirecting user for this point , with this approach
            # i can do that with delete_view but not with ajax
            # for now its use the hardcoded redirection to heroku by js
            return JsonResponse({
                'status': 1, 'message': "great"
            })

    messages.warning(request, f'have some issue with this  !')
    return JsonResponse({
        'status': 0, 'message': "Server error"
    })


def render_pdf_view(request, pk):
    template_path = 'reports/pdf_to.html'
    report_obj = get_object_or_404(Report, pk=pk)
    # all style must be added manual as css styling
    context = {
        'report_obj': report_obj
    }
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    # if download
    # response['Content-Disposition'] = 'attachment; filename="report.pdf"'
    # if display
    response['Content-Disposition'] = 'filename="report.pdf"'
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(
        html, dest=response, link_callback=link_callback)
    # if error then show some funy view
    if pisa_status.err:
        return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

reports/templates/reports/detail.html
{% extends 'base.html' %}
{% load static %}

{% block scripts %}
    <script src="{% static "reports/report.js" %}" defer></script>
{% endblock scripts %}

{% block content %}
    <div class="container">
        <h3> Details for {{ report_obj.name }} :</h3>
        <div class="row">
            <div class="col-sm-6">
                <h5>Remarks by {{ report_obj.author.user }}</h5>
                <p>{{ report_obj.remarks }}</p>
            </div>
            <div class="col-sm-6">
                <img src="{{ report_obj.image.url }}" class="img-fluid" alt="...">
            </div>
        </div>

        {% if user.is_authenticated %}
            {% if report_obj.author.user == user %}
                <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    Delete report
                </button>
            {% endif %}
        {% endif %}
        <a href="{% url 'reports:pdf_view' pk=report_obj.pk %}">
            <button type="button" class="btn btn-info">PDF</button>
        </a>


        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Confirm Deletion</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <form id="form_delete" action="{% url 'reports:list' %}" method="POST">
                        <div class="modal-body">
                            {% csrf_token %}
                            <p>are you sure ? </p>
                            {{ form.text.as_hidden }}
                            <p hidden id="transfer"> {{ report_obj.pk }} </p>

                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button id="delete_btn" type="submit" class="btn btn-danger">delete</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>


    </div>
{% endblock content %}

reports/templates/reports/home_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h3> List </h3>
    {% if reports_list %}

        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Created by</th>
                <th scope="col">Date</th>
            </tr>
            </thead>
            <tbody>
            {% for report in reports_list %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td><a href="{{ report.get_absolute_url }}">{{ report.name }}</a></td>
                    <td>{{ report.author.user }}</td>
                    <td>{{ report.created }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>




    {% endif %}

{% endblock content %}

reports/templates/reports/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h3> List </h3>
    {% if reports_list %}

        <table class="table table-striped table-hover">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Created by</th>
                <th scope="col">Date</th>
                <th scope="col">pdf</th>
            </tr>
            </thead>
            <tbody>
            {% for report in reports_list %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td><a href="{{ report.get_absolute_url }}">{{ report.name }}</a></td>
                    <td>{{ report.author.user }}</td>
                    <td>{{ report.created }}</td>
                    <td><a href="{% url 'reports:pdf_view' pk=report.pk %}">pdf</a></td>

                </tr>
            {% endfor %}
            </tbody>
        </table>




    {% endif %}

{% endblock content %}

reports/templates/reports/pdf_to.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    {% comment %}
    must add all style manual
    {% endcomment %}

    <style>
        body {

        }

        .title {

            text-align: center;
        }

        .sig {
            text-align: right;
        }

        .graph {
            padding: 5px;
            width: 600px;
        }
    </style>

</head>
<body>
<header>
    <h1 class="title">{{ report_obj.name }}</h1>
    <hr>
</header>

<main>
    <h4>Remarks: </h4>
    <p> {{ report_obj.remarks }}</p>

    <!--  todo cant upload picture from s3 -->
    <img src="{{ report_obj.image.path }}" class="graph" alt="...">
</main>

<footer>
    <hr>
    <div class="sig">
        <p>created : {{ report_obj.created }}</p>
        <p>by: {{ report_obj.author.user }}</p>
    </div>
</footer>
</body>
</html>