profiles/urls.py
from django.urls import path
from .views import profile_view

app_name = 'profile'

urlpatterns = [
    path('', profile_view, name='home')
]

reports/urls.py
from django.urls import path
from .views import (create_report_view, ReportslistView,
                    ReportDetailView, delete_report, render_pdf_view)

app_name = "reports"

urlpatterns = [
    path('create_report/', create_report_view, name="create_report"),
    path('list/', ReportslistView.as_view(), name="list"),
    path('detail/<int:pk>', ReportDetailView.as_view(), name="detail"),
    path('delete/', delete_report, name="delete_report"),
    path('render_pdf/<int:pk>', render_pdf_view, name="pdf_view"),

]

root/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import register, readme_view
from django.contrib.auth import views as auth_views

app_name = 'root_space'

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('sales.urls')),  # home page hosting
    path("customers/", include('customers.urls')),
    path("profile/", include('profiles.urls')),
    path("reports/", include('reports.urls')),
    path('regster/', register, name='register_user'),
    path('login/', auth_views.LoginView.as_view(template_name='root/login.html'), name='login_user'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout_user'),
    path('readme/', readme_view, name='readme_view'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

sales/urls.py
from django.urls import path
from .views import (home_view, SaleListView, SalesDetailView,
                    upload_csv_files)

app_name = 'sales'

urlpatterns = [
    path('', home_view, name='home'),
    path('sales/', SaleListView.as_view(), name='list'),
    path('sales/<int:pk>/', SalesDetailView.as_view(), name='detail'),
    path('upload_csv/', upload_csv_files, name='upload_csv'),



]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="{% static "main.css" %}">
    {# additional scripting #}
    {% block scripts %}
    {% endblock scripts %}

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    {% comment %}
    using bootstrap 5
    https://getbootstrap.com/docs/5.0/components/navbar/
    {% endcomment %}
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>SuperOne-1</title>
    {% endif %}

    <link rel="icon" href="{% static 'media/nav_icon.png' %}" type="image/png">
</head>
<body>

<nav>
    {% include 'navbar.html' %}
</nav>

{# messages #}
<div class="container mt-3">
    {% if messages %}
        {% for element in messages %}

            <div class="alert alert-{{ element.tags }} alert-dismissible fade show" role="alert">
                {{ element }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>

        {% endfor %}
    {% endif %}
</div>


{# end messags #}

{# main page data #}
<div class="container mt-3 mb-3">
    {% block content %}
    {% endblock content %}
</div>


<footer>
    {% include "footer.html" %}
</footer>


<!-- Option 2: Separate Popper and Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js"
        integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT"
        crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

</body>
</html>

templates/footer.html
{% load static %}

<div class="fixed-bottom ">
    <nav class="navbar navbar-expand-lg navbar-light bg-light mt-3">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'sales:home' %}">SaleApp</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                {% comment %}
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Link</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            Dropdown
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="#">Action</a></li>
                            <li><a class="dropdown-item" href="#">Another action</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                    </li>
                </ul>
                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
                {% endcomment %}
            </div>
        </div>
    </nav>
</div>

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img src="{% static 'media/nav_icon.png' %}" alt="" width="30" height="24">
        </a>

        <a class="navbar-brand" href="{% url 'sales:home' %}">SaleApp</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'sales:list' %}">Sales</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'reports:list' %}">Reports</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'readme_view' %}">Readme</a>
                </li>

                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'profile:home' %}">Profile</a>
                    </li>
                {% endif %}
            </ul>

            <div class="d-flex">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'logout_user' %}">LogOut</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'login_user' %}">LogIn</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'register_user' %}">Register</a>
                        </li>
                    {% endif %}

                    {% if user.is_superuser %}
                        <li class="nav-item">
                            <a class="nav-link " style="color: red" href="{% url 'admin:index' %}" tabindex="-1"
                               aria-disabled="true">Admin</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</nav>